/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWeekdayPatternsRouteImport } from './routes/api/weekday-patterns'
import { Route as ApiStockoutRiskRouteImport } from './routes/api/stockout-risk'
import { Route as ApiResetRouteImport } from './routes/api/reset'
import { Route as ApiMultiHourLeadersRouteImport } from './routes/api/multi-hour-leaders'
import { Route as ApiMetricsRouteImport } from './routes/api/metrics'
import { Route as ApiHourlyPeakAnalysisRouteImport } from './routes/api/hourly-peak-analysis'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiCategoryLeadersRouteImport } from './routes/api/category-leaders'
import { Route as ApiWithdrawalsHourBreakdownRouteImport } from './routes/api/withdrawals.hour-breakdown'
import { Route as ApiSyncRunsRouteImport } from './routes/api/sync.runs'
import { Route as ApiSyncProgressRouteImport } from './routes/api/sync.progress'
import { Route as ApiSyncLogsRouteImport } from './routes/api/sync.logs'
import { Route as ApiSettingsSupabaseRouteImport } from './routes/api/settings.supabase'
import { Route as ApiSettingsSchedulerRouteImport } from './routes/api/settings.scheduler'
import { Route as ApiSettingsEmailRouteImport } from './routes/api/settings.email'
import { Route as ApiProductsWithdrawalActivityRouteImport } from './routes/api/products.withdrawal-activity'
import { Route as ApiPlatformsPlatformRouteImport } from './routes/api/platforms.$platform'
import { Route as ApiDiagnosticsErrorRouteImport } from './routes/api/diagnostics.error'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth.login'
import { Route as ApiAnalyticsRevisionRouteImport } from './routes/api/analytics.revision'
import { Route as ApiAnalyticsHourlyWithdrawalsRouteImport } from './routes/api/analytics.hourly-withdrawals'
import { Route as ApiAnalyticsDashboardOverviewRouteImport } from './routes/api/analytics.dashboard-overview'
import { Route as ApiAnalyticsAccuracyCheckRouteImport } from './routes/api/analytics.accuracy-check'
import { Route as ApiSettingsSupabaseTestRouteImport } from './routes/api/settings.supabase.test'
import { Route as ApiSettingsEmailTestRouteImport } from './routes/api/settings.email.test'
import { Route as ApiPublicHooksReaperRouteImport } from './routes/api/public/hooks/reaper'
import { Route as ApiPlatformsPlatformTestRouteImport } from './routes/api/platforms.$platform.test'
import { Route as ApiPlatformsPlatformSyncRouteImport } from './routes/api/platforms.$platform.sync'
import { Route as ApiAnalyticsHourlyWithdrawalsHourProductsRouteImport } from './routes/api/analytics.hourly-withdrawals.$hour.products'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeekdayPatternsRoute = ApiWeekdayPatternsRouteImport.update({
  id: '/api/weekday-patterns',
  path: '/api/weekday-patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStockoutRiskRoute = ApiStockoutRiskRouteImport.update({
  id: '/api/stockout-risk',
  path: '/api/stockout-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResetRoute = ApiResetRouteImport.update({
  id: '/api/reset',
  path: '/api/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMultiHourLeadersRoute = ApiMultiHourLeadersRouteImport.update({
  id: '/api/multi-hour-leaders',
  path: '/api/multi-hour-leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetricsRoute = ApiMetricsRouteImport.update({
  id: '/api/metrics',
  path: '/api/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHourlyPeakAnalysisRoute = ApiHourlyPeakAnalysisRouteImport.update({
  id: '/api/hourly-peak-analysis',
  path: '/api/hourly-peak-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoryLeadersRoute = ApiCategoryLeadersRouteImport.update({
  id: '/api/category-leaders',
  path: '/api/category-leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWithdrawalsHourBreakdownRoute =
  ApiWithdrawalsHourBreakdownRouteImport.update({
    id: '/api/withdrawals/hour-breakdown',
    path: '/api/withdrawals/hour-breakdown',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSyncRunsRoute = ApiSyncRunsRouteImport.update({
  id: '/api/sync/runs',
  path: '/api/sync/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncProgressRoute = ApiSyncProgressRouteImport.update({
  id: '/api/sync/progress',
  path: '/api/sync/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncLogsRoute = ApiSyncLogsRouteImport.update({
  id: '/api/sync/logs',
  path: '/api/sync/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsSupabaseRoute = ApiSettingsSupabaseRouteImport.update({
  id: '/api/settings/supabase',
  path: '/api/settings/supabase',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsSchedulerRoute = ApiSettingsSchedulerRouteImport.update({
  id: '/api/settings/scheduler',
  path: '/api/settings/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsEmailRoute = ApiSettingsEmailRouteImport.update({
  id: '/api/settings/email',
  path: '/api/settings/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsWithdrawalActivityRoute =
  ApiProductsWithdrawalActivityRouteImport.update({
    id: '/api/products/withdrawal-activity',
    path: '/api/products/withdrawal-activity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlatformsPlatformRoute = ApiPlatformsPlatformRouteImport.update({
  id: '/api/platforms/$platform',
  path: '/api/platforms/$platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagnosticsErrorRoute = ApiDiagnosticsErrorRouteImport.update({
  id: '/api/diagnostics/error',
  path: '/api/diagnostics/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRevisionRoute = ApiAnalyticsRevisionRouteImport.update({
  id: '/api/analytics/revision',
  path: '/api/analytics/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsHourlyWithdrawalsRoute =
  ApiAnalyticsHourlyWithdrawalsRouteImport.update({
    id: '/api/analytics/hourly-withdrawals',
    path: '/api/analytics/hourly-withdrawals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAnalyticsDashboardOverviewRoute =
  ApiAnalyticsDashboardOverviewRouteImport.update({
    id: '/api/analytics/dashboard-overview',
    path: '/api/analytics/dashboard-overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAnalyticsAccuracyCheckRoute =
  ApiAnalyticsAccuracyCheckRouteImport.update({
    id: '/api/analytics/accuracy-check',
    path: '/api/analytics/accuracy-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSettingsSupabaseTestRoute = ApiSettingsSupabaseTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiSettingsSupabaseRoute,
} as any)
const ApiSettingsEmailTestRoute = ApiSettingsEmailTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiSettingsEmailRoute,
} as any)
const ApiPublicHooksReaperRoute = ApiPublicHooksReaperRouteImport.update({
  id: '/api/public/hooks/reaper',
  path: '/api/public/hooks/reaper',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlatformsPlatformTestRoute =
  ApiPlatformsPlatformTestRouteImport.update({
    id: '/test',
    path: '/test',
    getParentRoute: () => ApiPlatformsPlatformRoute,
  } as any)
const ApiPlatformsPlatformSyncRoute =
  ApiPlatformsPlatformSyncRouteImport.update({
    id: '/sync',
    path: '/sync',
    getParentRoute: () => ApiPlatformsPlatformRoute,
  } as any)
const ApiAnalyticsHourlyWithdrawalsHourProductsRoute =
  ApiAnalyticsHourlyWithdrawalsHourProductsRouteImport.update({
    id: '/$hour/products',
    path: '/$hour/products',
    getParentRoute: () => ApiAnalyticsHourlyWithdrawalsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/category-leaders': typeof ApiCategoryLeadersRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/hourly-peak-analysis': typeof ApiHourlyPeakAnalysisRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/multi-hour-leaders': typeof ApiMultiHourLeadersRoute
  '/api/reset': typeof ApiResetRoute
  '/api/stockout-risk': typeof ApiStockoutRiskRoute
  '/api/weekday-patterns': typeof ApiWeekdayPatternsRoute
  '/api/analytics/accuracy-check': typeof ApiAnalyticsAccuracyCheckRoute
  '/api/analytics/dashboard-overview': typeof ApiAnalyticsDashboardOverviewRoute
  '/api/analytics/hourly-withdrawals': typeof ApiAnalyticsHourlyWithdrawalsRouteWithChildren
  '/api/analytics/revision': typeof ApiAnalyticsRevisionRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/diagnostics/error': typeof ApiDiagnosticsErrorRoute
  '/api/platforms/$platform': typeof ApiPlatformsPlatformRouteWithChildren
  '/api/products/withdrawal-activity': typeof ApiProductsWithdrawalActivityRoute
  '/api/settings/email': typeof ApiSettingsEmailRouteWithChildren
  '/api/settings/scheduler': typeof ApiSettingsSchedulerRoute
  '/api/settings/supabase': typeof ApiSettingsSupabaseRouteWithChildren
  '/api/sync/logs': typeof ApiSyncLogsRoute
  '/api/sync/progress': typeof ApiSyncProgressRoute
  '/api/sync/runs': typeof ApiSyncRunsRoute
  '/api/withdrawals/hour-breakdown': typeof ApiWithdrawalsHourBreakdownRoute
  '/api/platforms/$platform/sync': typeof ApiPlatformsPlatformSyncRoute
  '/api/platforms/$platform/test': typeof ApiPlatformsPlatformTestRoute
  '/api/public/hooks/reaper': typeof ApiPublicHooksReaperRoute
  '/api/settings/email/test': typeof ApiSettingsEmailTestRoute
  '/api/settings/supabase/test': typeof ApiSettingsSupabaseTestRoute
  '/api/analytics/hourly-withdrawals/$hour/products': typeof ApiAnalyticsHourlyWithdrawalsHourProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/category-leaders': typeof ApiCategoryLeadersRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/hourly-peak-analysis': typeof ApiHourlyPeakAnalysisRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/multi-hour-leaders': typeof ApiMultiHourLeadersRoute
  '/api/reset': typeof ApiResetRoute
  '/api/stockout-risk': typeof ApiStockoutRiskRoute
  '/api/weekday-patterns': typeof ApiWeekdayPatternsRoute
  '/api/analytics/accuracy-check': typeof ApiAnalyticsAccuracyCheckRoute
  '/api/analytics/dashboard-overview': typeof ApiAnalyticsDashboardOverviewRoute
  '/api/analytics/hourly-withdrawals': typeof ApiAnalyticsHourlyWithdrawalsRouteWithChildren
  '/api/analytics/revision': typeof ApiAnalyticsRevisionRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/diagnostics/error': typeof ApiDiagnosticsErrorRoute
  '/api/platforms/$platform': typeof ApiPlatformsPlatformRouteWithChildren
  '/api/products/withdrawal-activity': typeof ApiProductsWithdrawalActivityRoute
  '/api/settings/email': typeof ApiSettingsEmailRouteWithChildren
  '/api/settings/scheduler': typeof ApiSettingsSchedulerRoute
  '/api/settings/supabase': typeof ApiSettingsSupabaseRouteWithChildren
  '/api/sync/logs': typeof ApiSyncLogsRoute
  '/api/sync/progress': typeof ApiSyncProgressRoute
  '/api/sync/runs': typeof ApiSyncRunsRoute
  '/api/withdrawals/hour-breakdown': typeof ApiWithdrawalsHourBreakdownRoute
  '/api/platforms/$platform/sync': typeof ApiPlatformsPlatformSyncRoute
  '/api/platforms/$platform/test': typeof ApiPlatformsPlatformTestRoute
  '/api/public/hooks/reaper': typeof ApiPublicHooksReaperRoute
  '/api/settings/email/test': typeof ApiSettingsEmailTestRoute
  '/api/settings/supabase/test': typeof ApiSettingsSupabaseTestRoute
  '/api/analytics/hourly-withdrawals/$hour/products': typeof ApiAnalyticsHourlyWithdrawalsHourProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/category-leaders': typeof ApiCategoryLeadersRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/hourly-peak-analysis': typeof ApiHourlyPeakAnalysisRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/multi-hour-leaders': typeof ApiMultiHourLeadersRoute
  '/api/reset': typeof ApiResetRoute
  '/api/stockout-risk': typeof ApiStockoutRiskRoute
  '/api/weekday-patterns': typeof ApiWeekdayPatternsRoute
  '/api/analytics/accuracy-check': typeof ApiAnalyticsAccuracyCheckRoute
  '/api/analytics/dashboard-overview': typeof ApiAnalyticsDashboardOverviewRoute
  '/api/analytics/hourly-withdrawals': typeof ApiAnalyticsHourlyWithdrawalsRouteWithChildren
  '/api/analytics/revision': typeof ApiAnalyticsRevisionRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/diagnostics/error': typeof ApiDiagnosticsErrorRoute
  '/api/platforms/$platform': typeof ApiPlatformsPlatformRouteWithChildren
  '/api/products/withdrawal-activity': typeof ApiProductsWithdrawalActivityRoute
  '/api/settings/email': typeof ApiSettingsEmailRouteWithChildren
  '/api/settings/scheduler': typeof ApiSettingsSchedulerRoute
  '/api/settings/supabase': typeof ApiSettingsSupabaseRouteWithChildren
  '/api/sync/logs': typeof ApiSyncLogsRoute
  '/api/sync/progress': typeof ApiSyncProgressRoute
  '/api/sync/runs': typeof ApiSyncRunsRoute
  '/api/withdrawals/hour-breakdown': typeof ApiWithdrawalsHourBreakdownRoute
  '/api/platforms/$platform/sync': typeof ApiPlatformsPlatformSyncRoute
  '/api/platforms/$platform/test': typeof ApiPlatformsPlatformTestRoute
  '/api/public/hooks/reaper': typeof ApiPublicHooksReaperRoute
  '/api/settings/email/test': typeof ApiSettingsEmailTestRoute
  '/api/settings/supabase/test': typeof ApiSettingsSupabaseTestRoute
  '/api/analytics/hourly-withdrawals/$hour/products': typeof ApiAnalyticsHourlyWithdrawalsHourProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/category-leaders'
    | '/api/dashboard'
    | '/api/health'
    | '/api/hourly-peak-analysis'
    | '/api/metrics'
    | '/api/multi-hour-leaders'
    | '/api/reset'
    | '/api/stockout-risk'
    | '/api/weekday-patterns'
    | '/api/analytics/accuracy-check'
    | '/api/analytics/dashboard-overview'
    | '/api/analytics/hourly-withdrawals'
    | '/api/analytics/revision'
    | '/api/auth/login'
    | '/api/diagnostics/error'
    | '/api/platforms/$platform'
    | '/api/products/withdrawal-activity'
    | '/api/settings/email'
    | '/api/settings/scheduler'
    | '/api/settings/supabase'
    | '/api/sync/logs'
    | '/api/sync/progress'
    | '/api/sync/runs'
    | '/api/withdrawals/hour-breakdown'
    | '/api/platforms/$platform/sync'
    | '/api/platforms/$platform/test'
    | '/api/public/hooks/reaper'
    | '/api/settings/email/test'
    | '/api/settings/supabase/test'
    | '/api/analytics/hourly-withdrawals/$hour/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/category-leaders'
    | '/api/dashboard'
    | '/api/health'
    | '/api/hourly-peak-analysis'
    | '/api/metrics'
    | '/api/multi-hour-leaders'
    | '/api/reset'
    | '/api/stockout-risk'
    | '/api/weekday-patterns'
    | '/api/analytics/accuracy-check'
    | '/api/analytics/dashboard-overview'
    | '/api/analytics/hourly-withdrawals'
    | '/api/analytics/revision'
    | '/api/auth/login'
    | '/api/diagnostics/error'
    | '/api/platforms/$platform'
    | '/api/products/withdrawal-activity'
    | '/api/settings/email'
    | '/api/settings/scheduler'
    | '/api/settings/supabase'
    | '/api/sync/logs'
    | '/api/sync/progress'
    | '/api/sync/runs'
    | '/api/withdrawals/hour-breakdown'
    | '/api/platforms/$platform/sync'
    | '/api/platforms/$platform/test'
    | '/api/public/hooks/reaper'
    | '/api/settings/email/test'
    | '/api/settings/supabase/test'
    | '/api/analytics/hourly-withdrawals/$hour/products'
  id:
    | '__root__'
    | '/'
    | '/api/category-leaders'
    | '/api/dashboard'
    | '/api/health'
    | '/api/hourly-peak-analysis'
    | '/api/metrics'
    | '/api/multi-hour-leaders'
    | '/api/reset'
    | '/api/stockout-risk'
    | '/api/weekday-patterns'
    | '/api/analytics/accuracy-check'
    | '/api/analytics/dashboard-overview'
    | '/api/analytics/hourly-withdrawals'
    | '/api/analytics/revision'
    | '/api/auth/login'
    | '/api/diagnostics/error'
    | '/api/platforms/$platform'
    | '/api/products/withdrawal-activity'
    | '/api/settings/email'
    | '/api/settings/scheduler'
    | '/api/settings/supabase'
    | '/api/sync/logs'
    | '/api/sync/progress'
    | '/api/sync/runs'
    | '/api/withdrawals/hour-breakdown'
    | '/api/platforms/$platform/sync'
    | '/api/platforms/$platform/test'
    | '/api/public/hooks/reaper'
    | '/api/settings/email/test'
    | '/api/settings/supabase/test'
    | '/api/analytics/hourly-withdrawals/$hour/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCategoryLeadersRoute: typeof ApiCategoryLeadersRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiHourlyPeakAnalysisRoute: typeof ApiHourlyPeakAnalysisRoute
  ApiMetricsRoute: typeof ApiMetricsRoute
  ApiMultiHourLeadersRoute: typeof ApiMultiHourLeadersRoute
  ApiResetRoute: typeof ApiResetRoute
  ApiStockoutRiskRoute: typeof ApiStockoutRiskRoute
  ApiWeekdayPatternsRoute: typeof ApiWeekdayPatternsRoute
  ApiAnalyticsAccuracyCheckRoute: typeof ApiAnalyticsAccuracyCheckRoute
  ApiAnalyticsDashboardOverviewRoute: typeof ApiAnalyticsDashboardOverviewRoute
  ApiAnalyticsHourlyWithdrawalsRoute: typeof ApiAnalyticsHourlyWithdrawalsRouteWithChildren
  ApiAnalyticsRevisionRoute: typeof ApiAnalyticsRevisionRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiDiagnosticsErrorRoute: typeof ApiDiagnosticsErrorRoute
  ApiPlatformsPlatformRoute: typeof ApiPlatformsPlatformRouteWithChildren
  ApiProductsWithdrawalActivityRoute: typeof ApiProductsWithdrawalActivityRoute
  ApiSettingsEmailRoute: typeof ApiSettingsEmailRouteWithChildren
  ApiSettingsSchedulerRoute: typeof ApiSettingsSchedulerRoute
  ApiSettingsSupabaseRoute: typeof ApiSettingsSupabaseRouteWithChildren
  ApiSyncLogsRoute: typeof ApiSyncLogsRoute
  ApiSyncProgressRoute: typeof ApiSyncProgressRoute
  ApiSyncRunsRoute: typeof ApiSyncRunsRoute
  ApiWithdrawalsHourBreakdownRoute: typeof ApiWithdrawalsHourBreakdownRoute
  ApiPublicHooksReaperRoute: typeof ApiPublicHooksReaperRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weekday-patterns': {
      id: '/api/weekday-patterns'
      path: '/api/weekday-patterns'
      fullPath: '/api/weekday-patterns'
      preLoaderRoute: typeof ApiWeekdayPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stockout-risk': {
      id: '/api/stockout-risk'
      path: '/api/stockout-risk'
      fullPath: '/api/stockout-risk'
      preLoaderRoute: typeof ApiStockoutRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reset': {
      id: '/api/reset'
      path: '/api/reset'
      fullPath: '/api/reset'
      preLoaderRoute: typeof ApiResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/multi-hour-leaders': {
      id: '/api/multi-hour-leaders'
      path: '/api/multi-hour-leaders'
      fullPath: '/api/multi-hour-leaders'
      preLoaderRoute: typeof ApiMultiHourLeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metrics': {
      id: '/api/metrics'
      path: '/api/metrics'
      fullPath: '/api/metrics'
      preLoaderRoute: typeof ApiMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hourly-peak-analysis': {
      id: '/api/hourly-peak-analysis'
      path: '/api/hourly-peak-analysis'
      fullPath: '/api/hourly-peak-analysis'
      preLoaderRoute: typeof ApiHourlyPeakAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/category-leaders': {
      id: '/api/category-leaders'
      path: '/api/category-leaders'
      fullPath: '/api/category-leaders'
      preLoaderRoute: typeof ApiCategoryLeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/withdrawals/hour-breakdown': {
      id: '/api/withdrawals/hour-breakdown'
      path: '/api/withdrawals/hour-breakdown'
      fullPath: '/api/withdrawals/hour-breakdown'
      preLoaderRoute: typeof ApiWithdrawalsHourBreakdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/runs': {
      id: '/api/sync/runs'
      path: '/api/sync/runs'
      fullPath: '/api/sync/runs'
      preLoaderRoute: typeof ApiSyncRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/progress': {
      id: '/api/sync/progress'
      path: '/api/sync/progress'
      fullPath: '/api/sync/progress'
      preLoaderRoute: typeof ApiSyncProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/logs': {
      id: '/api/sync/logs'
      path: '/api/sync/logs'
      fullPath: '/api/sync/logs'
      preLoaderRoute: typeof ApiSyncLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/supabase': {
      id: '/api/settings/supabase'
      path: '/api/settings/supabase'
      fullPath: '/api/settings/supabase'
      preLoaderRoute: typeof ApiSettingsSupabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/scheduler': {
      id: '/api/settings/scheduler'
      path: '/api/settings/scheduler'
      fullPath: '/api/settings/scheduler'
      preLoaderRoute: typeof ApiSettingsSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/email': {
      id: '/api/settings/email'
      path: '/api/settings/email'
      fullPath: '/api/settings/email'
      preLoaderRoute: typeof ApiSettingsEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/withdrawal-activity': {
      id: '/api/products/withdrawal-activity'
      path: '/api/products/withdrawal-activity'
      fullPath: '/api/products/withdrawal-activity'
      preLoaderRoute: typeof ApiProductsWithdrawalActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platforms/$platform': {
      id: '/api/platforms/$platform'
      path: '/api/platforms/$platform'
      fullPath: '/api/platforms/$platform'
      preLoaderRoute: typeof ApiPlatformsPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diagnostics/error': {
      id: '/api/diagnostics/error'
      path: '/api/diagnostics/error'
      fullPath: '/api/diagnostics/error'
      preLoaderRoute: typeof ApiDiagnosticsErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/revision': {
      id: '/api/analytics/revision'
      path: '/api/analytics/revision'
      fullPath: '/api/analytics/revision'
      preLoaderRoute: typeof ApiAnalyticsRevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/hourly-withdrawals': {
      id: '/api/analytics/hourly-withdrawals'
      path: '/api/analytics/hourly-withdrawals'
      fullPath: '/api/analytics/hourly-withdrawals'
      preLoaderRoute: typeof ApiAnalyticsHourlyWithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/dashboard-overview': {
      id: '/api/analytics/dashboard-overview'
      path: '/api/analytics/dashboard-overview'
      fullPath: '/api/analytics/dashboard-overview'
      preLoaderRoute: typeof ApiAnalyticsDashboardOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/accuracy-check': {
      id: '/api/analytics/accuracy-check'
      path: '/api/analytics/accuracy-check'
      fullPath: '/api/analytics/accuracy-check'
      preLoaderRoute: typeof ApiAnalyticsAccuracyCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/supabase/test': {
      id: '/api/settings/supabase/test'
      path: '/test'
      fullPath: '/api/settings/supabase/test'
      preLoaderRoute: typeof ApiSettingsSupabaseTestRouteImport
      parentRoute: typeof ApiSettingsSupabaseRoute
    }
    '/api/settings/email/test': {
      id: '/api/settings/email/test'
      path: '/test'
      fullPath: '/api/settings/email/test'
      preLoaderRoute: typeof ApiSettingsEmailTestRouteImport
      parentRoute: typeof ApiSettingsEmailRoute
    }
    '/api/public/hooks/reaper': {
      id: '/api/public/hooks/reaper'
      path: '/api/public/hooks/reaper'
      fullPath: '/api/public/hooks/reaper'
      preLoaderRoute: typeof ApiPublicHooksReaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platforms/$platform/test': {
      id: '/api/platforms/$platform/test'
      path: '/test'
      fullPath: '/api/platforms/$platform/test'
      preLoaderRoute: typeof ApiPlatformsPlatformTestRouteImport
      parentRoute: typeof ApiPlatformsPlatformRoute
    }
    '/api/platforms/$platform/sync': {
      id: '/api/platforms/$platform/sync'
      path: '/sync'
      fullPath: '/api/platforms/$platform/sync'
      preLoaderRoute: typeof ApiPlatformsPlatformSyncRouteImport
      parentRoute: typeof ApiPlatformsPlatformRoute
    }
    '/api/analytics/hourly-withdrawals/$hour/products': {
      id: '/api/analytics/hourly-withdrawals/$hour/products'
      path: '/$hour/products'
      fullPath: '/api/analytics/hourly-withdrawals/$hour/products'
      preLoaderRoute: typeof ApiAnalyticsHourlyWithdrawalsHourProductsRouteImport
      parentRoute: typeof ApiAnalyticsHourlyWithdrawalsRoute
    }
  }
}

interface ApiAnalyticsHourlyWithdrawalsRouteChildren {
  ApiAnalyticsHourlyWithdrawalsHourProductsRoute: typeof ApiAnalyticsHourlyWithdrawalsHourProductsRoute
}

const ApiAnalyticsHourlyWithdrawalsRouteChildren: ApiAnalyticsHourlyWithdrawalsRouteChildren =
  {
    ApiAnalyticsHourlyWithdrawalsHourProductsRoute:
      ApiAnalyticsHourlyWithdrawalsHourProductsRoute,
  }

const ApiAnalyticsHourlyWithdrawalsRouteWithChildren =
  ApiAnalyticsHourlyWithdrawalsRoute._addFileChildren(
    ApiAnalyticsHourlyWithdrawalsRouteChildren,
  )

interface ApiPlatformsPlatformRouteChildren {
  ApiPlatformsPlatformSyncRoute: typeof ApiPlatformsPlatformSyncRoute
  ApiPlatformsPlatformTestRoute: typeof ApiPlatformsPlatformTestRoute
}

const ApiPlatformsPlatformRouteChildren: ApiPlatformsPlatformRouteChildren = {
  ApiPlatformsPlatformSyncRoute: ApiPlatformsPlatformSyncRoute,
  ApiPlatformsPlatformTestRoute: ApiPlatformsPlatformTestRoute,
}

const ApiPlatformsPlatformRouteWithChildren =
  ApiPlatformsPlatformRoute._addFileChildren(ApiPlatformsPlatformRouteChildren)

interface ApiSettingsEmailRouteChildren {
  ApiSettingsEmailTestRoute: typeof ApiSettingsEmailTestRoute
}

const ApiSettingsEmailRouteChildren: ApiSettingsEmailRouteChildren = {
  ApiSettingsEmailTestRoute: ApiSettingsEmailTestRoute,
}

const ApiSettingsEmailRouteWithChildren =
  ApiSettingsEmailRoute._addFileChildren(ApiSettingsEmailRouteChildren)

interface ApiSettingsSupabaseRouteChildren {
  ApiSettingsSupabaseTestRoute: typeof ApiSettingsSupabaseTestRoute
}

const ApiSettingsSupabaseRouteChildren: ApiSettingsSupabaseRouteChildren = {
  ApiSettingsSupabaseTestRoute: ApiSettingsSupabaseTestRoute,
}

const ApiSettingsSupabaseRouteWithChildren =
  ApiSettingsSupabaseRoute._addFileChildren(ApiSettingsSupabaseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCategoryLeadersRoute: ApiCategoryLeadersRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiHourlyPeakAnalysisRoute: ApiHourlyPeakAnalysisRoute,
  ApiMetricsRoute: ApiMetricsRoute,
  ApiMultiHourLeadersRoute: ApiMultiHourLeadersRoute,
  ApiResetRoute: ApiResetRoute,
  ApiStockoutRiskRoute: ApiStockoutRiskRoute,
  ApiWeekdayPatternsRoute: ApiWeekdayPatternsRoute,
  ApiAnalyticsAccuracyCheckRoute: ApiAnalyticsAccuracyCheckRoute,
  ApiAnalyticsDashboardOverviewRoute: ApiAnalyticsDashboardOverviewRoute,
  ApiAnalyticsHourlyWithdrawalsRoute:
    ApiAnalyticsHourlyWithdrawalsRouteWithChildren,
  ApiAnalyticsRevisionRoute: ApiAnalyticsRevisionRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiDiagnosticsErrorRoute: ApiDiagnosticsErrorRoute,
  ApiPlatformsPlatformRoute: ApiPlatformsPlatformRouteWithChildren,
  ApiProductsWithdrawalActivityRoute: ApiProductsWithdrawalActivityRoute,
  ApiSettingsEmailRoute: ApiSettingsEmailRouteWithChildren,
  ApiSettingsSchedulerRoute: ApiSettingsSchedulerRoute,
  ApiSettingsSupabaseRoute: ApiSettingsSupabaseRouteWithChildren,
  ApiSyncLogsRoute: ApiSyncLogsRoute,
  ApiSyncProgressRoute: ApiSyncProgressRoute,
  ApiSyncRunsRoute: ApiSyncRunsRoute,
  ApiWithdrawalsHourBreakdownRoute: ApiWithdrawalsHourBreakdownRoute,
  ApiPublicHooksReaperRoute: ApiPublicHooksReaperRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
